version: '3.8'

services:
  AutotechDB:
    image: mysql:5.7
    container_name: AutotechDB
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: urubu100
      MYSQL_DATABASE: AutotechDB
      MYSQL_USER: AutotechDB
      MYSQL_PASSWORD: urubu100
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    networks:
      app_net:
        ipv4_address: 172.20.0.2
        
  JavaJar:
    image: nathanbin/java-jar.jar:autotech
    container_name: AutotechJAR
    command: ["java", "-jar", "/app/autotech.jar"]
    stdin_open: true
    tty: true
    depends_on:
      - AutotechDB
    environment:
      - DATABASE_HOST=AutotechDB
      - DATABASE_PORT=3306
      - DATABASE_USER=AutotechDB
      - DATABASE_PASSWORD=urubu100
      - DATABASE_NAME=AutotechDB
    networks:
      app_net:
        ipv4_address: 172.20.0.3

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16